myMovieReviews/movie/urls.py
from django.urls import path 
from django.contrib import admin


from . import views

app_name = "movie"

urlpatterns = [
    path('', views.home, name='home'),
    path('create', views.create, name = "create"),
    path('movie/<int:id>', views.detail, name = "detail"),
    path('update/<int:id>',views.update, name='update'),
    path('delete/<int:id>',views.delete, name='delete'),
]

myMovieReviews/movie/models.py
from django.db import models
from re import T

# Create your models here.

class genrebox(models.Model):
    genrele = (('sf','sf'),('comic','comic'),('horror','horror'))

class Movie(models.Model):
    title = models.CharField(max_length=50, verbose_name="제목") #챠필드 최대길이,제목안쓰면 제목이라고 미리들어감?
    openyear = models.IntegerField(verbose_name="개봉년도")
    genre = models.CharField(max_length=50, choices=genrebox.genrele, default='sf')
    # genre = models.CharField(max_length=50, verbose_name="장르")
    score = models.IntegerField(verbose_name="별점")
    runningtime = models.IntegerField(verbose_name="러닝타임")
    content = models.TextField(verbose_name="리뷰")
    director = models.CharField(max_length=50, verbose_name="감독")
    actor = models.CharField(max_length=50, verbose_name="배우")

myMovieReviews/movie/views.py
from django.shortcuts import render, redirect
from .models import Movie, genrebox

# Create your views here.

def home(request):
    
    sort = request.GET.get('sort',7)
    print(sort)
    if sort == '1':
        movieinfo = Movie.objects.all().order_by('title') #__contains는 값이 있으면 가져온다?
    elif sort == '2':
        movieinfo = Movie.objects.all().order_by('-title')
    elif sort == '3':
        movieinfo = Movie.objects.all().order_by('score')
    elif sort == '4':
        movieinfo = Movie.objects.all().order_by('-score')
    elif sort == '5':
        movieinfo = Movie.objects.all().order_by('runningtime')
    elif sort == '6':
        movieinfo = Movie.objects.all().order_by('-runningtime')
    elif sort == '7':
        movieinfo = Movie.objects.all()
    else:
        movieinfo = Movie.objects.all()
        
    

    
    
    context = {
        "movieinfo":movieinfo,
        
        
    }
    return render(request,template_name="movie/home.html",context=context)


def create(request):
    genrename = genrebox.genrele
    print(genrename[0][0])
    if request.method == "POST":
        print(request.POST)
        title = request.POST["title"]
        openyear = request.POST["openyear"]
        genre = request.POST["genre"]
        score = request.POST["score"]
        runningtime = request.POST["runningtime"]
        content = request.POST["content"]
        director = request.POST["director"]
        actor = request.POST["actor"]
        Movie.objects.create(title=title,director=director,actor=actor, content=content, openyear=openyear, genre=genre, runningtime=runningtime, score=score)
        return redirect("/") #제출누르면 자동으로 홈으로가서 저장된거보여줌
    context = {
        "genrename":genrename
    }

    return render(request, template_name="movie/create.html", context=context)

def detail(request, id):
    movieinfo = Movie.objects.get(id=id)
    print(movieinfo)
    context = {
        "movieinfo": movieinfo,
        "hour": movieinfo.runningtime//60,
        "min": movieinfo.runningtime %60,
    }
    return render(request, template_name="movie/detail.html", context=context)    

def update(request, id):
    genrename = genrebox.genrele
    if request.method == "POST":
        print(request.POST)
        title = request.POST["title"]
        openyear = request.POST["openyear"]
        genre = request.POST["genre"]
        score = request.POST["score"]
        runningtime = request.POST["runningtime"]
        content = request.POST["content"]
        director = request.POST["director"]
        actor = request.POST["actor"]

        
        Movie.objects.filter(id=id).update(title=title,director=director,actor=actor, content=content, openyear=openyear, genre=genre, runningtime=runningtime, score=score)
        return redirect(f"/movie/{id}")


    movieinfo = Movie.objects.get(id=id)
    context = {
        "movieinfo": movieinfo,
        "genrename":genrename
    }
    return render(request, template_name="movie/update.html", context=context)

def delete(request,id):
    if request.method == "POST":
        Movie.objects.filter(id=id).delete()
        return redirect("/")

myMovieReviews/movie/templates/movie/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>리뷰 올리기</title>
  </head>
  <body>
    <form action="/create" method="post">
      {% csrf_token %}
      <h2>제목: <input type="text" name="title" placeholder="제목" /></h2>
      <p>
        개봉년도: <input type="number" name="openyear" placeholder="개봉년도" />
        장르: <select name="genre" id="">
          {% for genrename in genrename %}
          <option value="{{genrename.0}}">{{genrename.1}}</option>
          {% endfor %}
        </select>
        별점: <input type="number" name="score" placeholder="별점" />
        러닝타임:
        <input type="number" name="runningtime" placeholder="러닝타임" />
      </p>
      리뷰작성:
      <textarea
        name="content"
        id=""
        cols="30"
        rows="10"
        placeholder="리뷰"
      ></textarea>
      <p>
        감독: <input type="text" name="director" placeholder="감독" /> 배우:
        <input type="text" name="actor" placeholder="배우" />
      </p>
      <div>
        <input type="submit" value="제출" />
      </div>
    </form>
    <a href="{% url 'movie:home' %}">my Movie reviews</a>
  </body>
</html>

myMovieReviews/movie/templates/movie/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>상세화면</title>
  </head>
  <body>
    <article>
      <h1>제목: {{movieinfo.title}}</h1>
      <p>개봉년도: {{movieinfo.openyear}}</p>
      <p>장르: {{movieinfo.genre}}</p>
      <p>평점: {{movieinfo.score}}</p>
      <p>상영시간: {{hour}}시간 {{min}} 분  </p>
      <p>감독: {{movieinfo.director}}</p>
      <p>배우: {{movieinfo.actor}}</p>
      <div>리뷰: {{movieinfo.content}}</div>
    </article>

    <div>
      <!-- href 쉽게 작성하는법 urls파일에서 name으로 지정했던거이용 -->
      <a href="{% url 'movie:update' movieinfo.id %}">수정</a>
      <!-- 여기서 딜리트 post id가져오는건 지금 현제페이지 디테일페이지에 숫자적혀있는거 그거 그데로가저오는거 -->
      <form action="/delete/{{movieinfo.id}}" method="post">
        {% csrf_token %}
        <button>삭제</button>
      </form>
      <!-- <a href="/delete/{{post.id}}">삭제하기</a> 이렇게 링크로 쓰면안됨 -->
    </div>

    <div><a href="/">my Movie reviews</a></div>
  </body>
</html>

myMovieReviews/movie/templates/movie/home.html
<!DOCTYPE html>
<html lang="ko">
    
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/home.css'%}">
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>홈 화면</title>
  </head>
  <body>
    <div id="mainflex">
      <div ><h1 id="title">*나의 영화 리뷰</h1></div>
      <div id="top">
    {% load mathfilters %}
    <form action="{% url 'movie:home' %}">
        <button name="sort" value="1">제목오름차순</button>
        <button name="sort" value="2">제목내림차순</button>
        <button name="sort" value="3">별점오름차순</button>
        <button name="sort" value="4">별점내림차순</button>
        <button name="sort" value="5">상영시간오름차순</button>
        <button name="sort" value="6">상영시간내림차순</button>
        <button name="sort" value="7">등록순</button>
      </form>
      <a href="/create" id="newcon">리뷰작성</a>
      </div>
      <div id="main">
    {% for i in movieinfo %}
    
    <article>
      <h1><a href="/movie/{{i.id}}"> {{i.title}} </a></h1>
      <p>개봉년도: {{i.openyear}}</p>
      <p>장르: {{i.genre}}</p>
      <p>평점: {{i.score}}</p>
      <p>상영시간: {{ i.runningtime|intdiv:60 }}시간  {{ i.runningtime|mod:60 }}분</p>
    </article>
  
    {% endfor %}
  </div>

    
  </div>
  </body>
</html>

myMovieReviews/movie/templates/movie/update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>리뷰 올리기</title>
  </head>
  <body>
    <form action="/update/{{movieinfo.id}}" method="post">
      {% csrf_token %}
      <h2>
        제목:
        <input
          type="text"
          name="title"
          placeholder="제목"
          value="{{movieinfo.title}}"
        />
      </h2>
      <p>
        개봉년도:
        <input
          type="number"
          name="openyear"
          placeholder="개봉년도"
          value="{{movieinfo.openyear}}"
        />
        장르:
        <select name="genre" id="">
          {% for genrename in genrename %} 
          {% if movieinfo.genre == genrename.1%}
          <option selected="selected" value="{{genrename.0}}">
            {{genrename.1}}
          </option>

          {% else %}
          <option value="{{genrename.0}}">{{genrename.1}}</option>
          {% endif %} {% endfor %}
        </select>
        별점:
        <input
          type="number"
          name="score"
          placeholder="별점"
          value="{{movieinfo.score}}"
        />
        러닝타임:
        <input
          type="number"
          name="runningtime"
          placeholder="러닝타임"
          value="{{movieinfo.runningtime}}"
        />
      </p>
      리뷰작성:
      <textarea name="content" id="" cols="30" rows="10">
{{movieinfo.content}}</textarea
      >
      <p>
        감독:
        <input
          type="text"
          name="director"
          placeholder="감독"
          value="{{movieinfo.director}}"
        />
        배우:
        <input
          type="text"
          name="actor"
          placeholder="배우"
          value="{{movieinfo.actor}}"
        />
      </p>
      <div>
        <input type="submit" value="업데이트" />
      </div>
    </form>
    <a href="/">Home</a>
  </body>
</html>