SWIDEA_SITE/swidea/urls.py
from django.urls import path 
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "swidea"

urlpatterns = [
    path('', views.home, name='home'),
    path('create', views.create, name = "create"),
    path('swidea/<int:id>', views.detail, name = "detail"),
    path('update/<int:id>',views.update, name='update'),
    path('delete/<int:id>',views.delete, name='delete'),
    path('toolhome',views.toolhome, name='toolhome'),
    path('tooldetail/<int:id>',views.tooldetail, name='tooldetail'),
    path('toolcreate', views.toolcreate, name = "toolcreate"),
    path('toolupdate/<int:id>',views.toolupdate, name='toolupdate'),
    path('tooldelete/<int:id>',views.tooldelete, name='tooldelete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

SWIDEA_SITE/swidea/models.py
from django.db import models
from re import T

# Create your models here.

class swtool(models.Model):
    toolname = models.CharField(max_length=50, verbose_name="툴이름")
    tooltype = models.CharField(max_length=50, verbose_name="툴타입")
    toolcontent = models.TextField(verbose_name="툴내용")

class swidea(models.Model):
    ideaname = models.CharField(max_length=50, verbose_name="아이디어이름")
    ideaphoto = models.ImageField(blank=True,verbose_name="아이디어사진", null=True)
    ideacontent = models.TextField(verbose_name="아이디어내용")
    ideainterest = models.IntegerField(verbose_name="아이디어관심도")
    ideatool = models.ForeignKey(swtool,on_delete=models.CASCADE,related_name="아이디어툴")
    ideachoice = models.BooleanField(default=False, verbose_name="아이디어찜")

SWIDEA_SITE/swidea/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from .models import swidea, swtool
import datetime

# Create your views here.

def home(request):
    sort = request.GET.get('sort',None)
    print(sort)
    if sort == '1':
        ideainfo = swidea.objects.all().order_by('ideaname') #__contains는 값이 있으면 가져온다?
    elif sort == '2':
        ideainfo = swidea.objects.all().order_by('ideachoice')
    elif sort == '3':
        ideainfo = swidea.objects.all().order_by()
    elif sort == '4':
        ideainfo = swidea.objects.all().order_by('-id')
    else:
        ideainfo = swidea.objects.all()

    choice = request.GET.get('choice',None)
    if choice != None: 
        choiceidea = swidea.objects.filter(id=choice)
        if choiceidea[0].ideachoice == True:
            swidea.objects.filter(id=choice).update(ideachoice = False)
        else:
            swidea.objects.filter(id=choice).update(ideachoice = True)
    numidplus = request.GET.get('plus',None)
    if numidplus != None:
        a = swidea.objects.filter(id=numidplus)
        b = a[0].ideainterest
        swidea.objects.filter(id=numidplus).update(ideainterest= b+1)
    numidminus = request.GET.get('minus',None)
    if numidminus != None:
        a = swidea.objects.filter(id=numidminus)
        b = a[0].ideainterest
        swidea.objects.filter(id=numidminus).update(ideainterest= b-1)

    context = {
        "ideainfo":ideainfo, 
    }
    return render(request,template_name="swidea/home.html",context=context)

def create(request):
    toollist = swtool.objects.all()
    if request.method == "POST":
        ideaname = request.POST["ideaname"]
        ideaphoto = request.FILES.get("ideaphoto")
        ideacontent = request.POST["ideacontent"]
        ideainterest = request.POST["ideainterest"]
        ideatool = request.POST["ideatool"]
        ideatoolname = swtool.objects.get(id = ideatool)

        swidea.objects.create(ideaname = ideaname, ideaphoto = ideaphoto, ideacontent = ideacontent, ideainterest=ideainterest, ideatool=ideatoolname)
        a = swidea.objects.all()
        return redirect(f"/swidea/{a.last().id}")
    context = {
        "toollist" :toollist
    }
    return render(request, template_name="swidea/create.html", context=context)

def detail(request, id):
    ideainfo = swidea.objects.get(id=id)
    context = {
        "ideainfo": ideainfo,
    }
    return render(request, template_name="swidea/detail.html", context=context)

def update(request, id):
    toollist = swtool.objects.all()
    if request.method == "POST":
        ideaname = request.POST["ideaname"]
        ideaphoto = request.FILES.get("ideaphoto")
        ideacontent = request.POST["ideacontent"]
        ideainterest = request.POST["ideainterest"]
        ideatool = request.POST["ideatool"]
        clear = request.POST.get("clear")
        ideatoolname = swtool.objects.get(id = ideatool)
        print(ideaphoto,'rr')
        if clear == 'clear':
            swidea.objects.filter(id=id).update(ideaname = ideaname,ideaphoto=None,  ideacontent = ideacontent, ideainterest=ideainterest, ideatool=ideatoolname)
            return redirect(f"/swidea/{id}")
        else:
            if ideaphoto == None:
                swidea.objects.filter(id=id).update(ideaname = ideaname,  ideacontent = ideacontent, ideainterest=ideainterest, ideatool=ideatoolname)
                return redirect(f"/swidea/{id}")
            else:
                swidea.objects.filter(id=id).update(ideaname = ideaname,ideaphoto=ideaphoto,  ideacontent = ideacontent, ideainterest=ideainterest, ideatool=ideatoolname)
                return redirect(f"/swidea/{id}")
        
        # a = request.POST["input_check"]
        # print(a)
        # if a == 1:
        #     swidea.objects.filter(id=id).update(ideaname = ideaname,ideaphoto=ideaphoto,  ideacontent = ideacontent, ideainterest=ideainterest, ideatool=ideatoolname)
        #     return redirect(f"/swidea/{id}")
        # else:
        #     swidea.objects.filter(id=id).update(ideaname = ideaname,  ideacontent = ideacontent, ideainterest=ideainterest, ideatool=ideatoolname)
        #     return redirect(f"/swidea/{id}")
            
        # now = datetime.datetime.now()
        # timepath = now.strftime('/%Y%m%d/')
        # ideaphotopath = 'posts'+timepath+ideaphoto
        # swidea.objects.filter(id=id).update(ideaname = ideaname,ideaphoto=ideaphoto,  ideacontent = ideacontent, ideainterest=ideainterest, ideatool=ideatoolname)
        # return redirect(f"/swidea/{id}")


    ideainfo = swidea.objects.get(id=id)
    context = {
        "ideainfo": ideainfo,
        "toollist" :toollist,

    }
    return render(request, template_name="swidea/update.html", context=context)

def delete(request,id):
    if request.method == "POST":
        swidea.objects.filter(id=id).delete()
        return redirect("/")


def toolhome(request):
    toolinfo = swtool.objects.all()

    context = {
        "toolinfo":toolinfo, 
    }
    return render(request,template_name="swidea/toolhome.html",context=context)

def tooldetail(request,id):
    toolinfo = swtool.objects.get(id=id)
    ideainfo = swidea.objects.all()
    all_swidea = []
    for i in ideainfo: 
        if toolinfo == i.ideatool:
            all_swidea.append(i)

    context = {
        "toolinfo": toolinfo,
        "all_swidea": all_swidea,
    }
    return render(request, template_name="swidea/tooldetail.html", context=context)


def toolcreate(request):
    if request.method == "POST":
        toolname = request.POST["toolname"]
        tooltype = request.POST["tooltype"]
        toolcontent = request.POST["toolcontent"]

        swtool.objects.create(toolname = toolname, tooltype=tooltype, toolcontent=toolcontent)
        a = swtool.objects.all()
        return redirect(f"/tooldetail/{a.last().id}")
    context = {
    }
    return render(request, template_name="swidea/toolcreate.html", context=context)


def toolupdate(request,id):
    if request.method == "POST":
        toolname = request.POST["toolname"]
        tooltype = request.POST["tooltype"]
        toolcontent = request.POST["toolcontent"]

        swtool.objects.filter(id=id).update(toolname = toolname, tooltype=tooltype, toolcontent=toolcontent)
        return redirect(f"/tooldetail/{id}")

    toolinfo = swtool.objects.get(id = id)
    context = {
        "toolinfo": toolinfo,
    }
    return render(request, template_name="swidea/toolupdate.html", context=context)

def tooldelete(request,id):
    if request.method == "POST":
        swtool.objects.filter(id=id).delete()
        return redirect("/toolhome")

SWIDEA_SITE/swidea/templates/swidea/create.html
<!DOCTYPE html>
<html lang="ko">
  {% load static %}
  <head>
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>아이디어 등록</title>
  </head>
  <body>
    <form action="/create" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <h2>
        <input type="text" name="ideaname" placeholder="아이디어명" />
      </h2>
      <p>
        <input type="file" name="ideaphoto">
      </p>
      <textarea name="ideacontent" id="" cols="30" rows="10"></textarea>
      <p><input type="number" name="ideainterest" placeholder="아이디어관심도" /></p>

      <select name="ideatool" id="">
        {% for toolname in toollist %}
        <option value="{{toolname.id}}">{{toolname.toolname}}</option>
        {% endfor %}
      </select>

      <div>
        
        <input type="submit" value="제출" />
      </div>
    </form>
    <a href="{% url 'swidea:home' %}">home</a>
  </body>
</html>

SWIDEA_SITE/swidea/templates/swidea/detail.html
<!DOCTYPE html>
<html lang="ko">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>상세화면</title>
  </head>
  <body>
    <article>
      <h2>제목 : {{ ideainfo.ideaname }}</h2>
      {% if ideainfo.ideaphoto %}
      <p>
        <img src="{{ ideainfo.ideaphoto.url }}"/>
      </p>
        {% endif %}

      <div>아이디어 설명 {{ideainfo.ideacontent}}</div>
      <p>예상 개발 툴 <a href="/tooldetail/{{ideainfo.ideatool.id}}">  {{ideainfo.ideatool.toolname}}</a></p>
      <p>아이디어 관심도 {{ideainfo.ideainterest}}</p>
      <p>찜 {{ideainfo.ideachoice}}</p>

    </article>

    <div>
      <!-- href 쉽게 작성하는법 urls파일에서 name으로 지정했던거이용 -->
      업데이트 : <a href="{% url 'swidea:update' ideainfo.id %}">update</a>
      <!-- 여기서 딜리트 post id가져오는건 지금 현제페이지 디테일페이지에 숫자적혀있는거 그거 그데로가저오는거 -->
      <form action="{% url 'swidea:delete' ideainfo.id %}" method="post">
        {% csrf_token %}
        <button>삭제</button>
      </form>
      <!-- <a href="/delete/{{post.id}}">삭제하기</a> 이렇게 링크로 쓰면안됨 -->
    </div>

    <div>홈 화면으로 가기: <a href="/">Home</a></div>
  </body>
</html>

SWIDEA_SITE/swidea/templates/swidea/home.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>아이디어 매니저</h1>
    <a href="/create">아이디어작성</a>
    <a href="/toolhome">툴홈</a>
    <form action="{% url 'swidea:home' %}" >
        <select name="sort" onchange="this.form.submit()">
            <option selected="selected"  value="none">--정렬기준--</option>
            <option value="1">이름순</option>
            <option value="2">찜순</option>
            <option value="3">등록순</option>
            <option value="4">최신순</option>
        </select>
    </form>

    
    
    {% for ideainfo in ideainfo %}

    <article>
      {% if ideainfo.ideaphoto %}
    <p>
      <img src="{{ ideainfo.ideaphoto.url }}"/>
    </p>
      {% endif %}
      <div>
      <a href="/swidea/{{ideainfo.id}}">
        {{ideainfo.ideaname}}
      </a>
      <p>예상 개발 툴 {{ideainfo.ideatool.toolname}}</p>
      <form action="{% url 'swidea:home' %}">
      <p>아이디어 관심도 {{ideainfo.ideainterest}}</p>
      <button name="plus"  value="{{ideainfo.id}}">+</button>
      <button name="minus" value="{{ideainfo.id}}">-</button>
    </form>
      <p>찜유무 {{ideainfo.ideachoice}}</p>
      <form action="{% url 'swidea:home' %}">
        {% if ideainfo.ideachoice %}
        <button name="choice"  value="{{ideainfo.id}}">찜해제</button>
        {% else %}
        <button name="choice" value="{{ideainfo.id}}">찜</button>
        {% endif %}
      </form>

    </div>
    </article>
    {% endfor %}
</body>
</html>

SWIDEA_SITE/swidea/templates/swidea/toolcreate.html
<!DOCTYPE html>
<html lang="ko">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>툴 등록</title>
  </head>
  <body>
    <form action="/toolcreate" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <h2>
        <input type="text" name="toolname" placeholder="툴이름" />
      </h2>
      <p><input type="text" name="tooltype" placeholder="툴종류" /></p>
      <textarea name="toolcontent" id="" cols="30" rows="10"></textarea>


      <div>
        
        <input type="submit" value="제출" />
      </div>
    </form>
    <a href="{% url 'swidea:toolhome' %}">toolhome</a>
  </body>
</html>

SWIDEA_SITE/swidea/templates/swidea/tooldetail.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tool디테일</title>
</head>
<body>
    <h1>개발툴 디테일</h1>
    <article>
        <h2>{{ toolinfo.toolname }}</h2>

        <p>{{toolinfo.tooltype}}</p>
        <p>{{toolinfo.toolcontent}}</p>

        <p>만들수있는 sw목록</p>
        <div>
            {% for ideainfo in all_swidea %}
            <a href="{% url 'swidea:detail' ideainfo.id %}">{{ ideainfo.ideaname }}</a>
            {% endfor %}
        </div>
    </article>
    <div>
        <!-- href 쉽게 작성하는법 urls파일에서 name으로 지정했던거이용 -->
        업데이트 : <a href="{% url 'swidea:toolupdate' toolinfo.id %}">update</a>
        <!-- 여기서 딜리트 post id가져오는건 지금 현제페이지 디테일페이지에 숫자적혀있는거 그거 그데로가저오는거 -->
        <form action="{% url 'swidea:tooldelete' toolinfo.id %}" method="post">
          {% csrf_token %}
          <button>삭제</button>
        </form>
        <!-- <a href="/delete/{{post.id}}">삭제하기</a> 이렇게 링크로 쓰면안됨 -->
      </div>
      <div>툴홈 화면으로 가기: <a href="/toolhome">Home</a></div>
</body>
</html>

SWIDEA_SITE/swidea/templates/swidea/toolhome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>toolhome</title>
</head>
<body>
    <h1>DevTool Lise</h1>
    <a href="/">메인홈으로</a>
    <a href="/toolcreate">새툴작성</a>
    {% for toolinfo in toolinfo %}
    <article>
        <a href="/tooldetail/{{toolinfo.id}}">{{toolinfo.toolname}}</a>
        <p>{{toolinfo.tooltype}}</p>
        <p>{{toolinfo.toolcontent}}</p>

    </article>
    {% endfor %}
</body>
</html>

SWIDEA_SITE/swidea/templates/swidea/toolupdate.html
<!DOCTYPE html>
<html lang="ko">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>툴 등록</title>
  </head>
  <body>
    <form action="/toolupdate/{{toolinfo.id}}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <h2>
        <input type="text" name="toolname" placeholder="툴이름" value="{{toolinfo.toolname}}"/>
      </h2>
      <p><input type="text" name="tooltype" placeholder="툴종류" value="{{toolinfo.tooltype}}" /></p>
      <textarea name="toolcontent" id="" cols="30" rows="10">{{toolinfo.toolcontent}}</textarea>


      <div>
        
        <input type="submit" value="제출" />
      </div>
    </form>
    <a href="{% url 'swidea:toolhome' %}">toolhome</a>
  </body>
</html>

SWIDEA_SITE/swidea/templates/swidea/update.html
<!DOCTYPE html>
<html lang="ko">
  {% load static %}
  <head>
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>아이디어 등록</title>

  </head>
  <body>

    <form action="/update/{{ideainfo.id}}" name = "ideaphoto" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <h2>
        
        <input type="text" name="ideaname" placeholder="아이디어명" value="{{ideainfo.ideaname}}"/>
      </h2>
      {% if ideainfo.ideaphoto %}
      
      <p>이전사진 {{ideainfo.ideaphoto.url}} <input type="checkbox" name="clear" value="clear" id="clear"><label for="clear">clear</label>  </p>

      {% endif %}
      <p>
        <input type="file" name="ideaphoto" >
      </p>
      <textarea name="ideacontent" id="" cols="30" rows="10" >{{ideainfo.ideacontent}}</textarea>
      <p><input type="number" name="ideainterest" placeholder="아이디어관심도" value="{{ideainfo.ideainterest}}" /></p>

      <select name="ideatool" id="">
        {% for toolname in toollist %}
        {% if ideainfo.ideatool == toolname %}
        <option selected="selected" value="{{toolname.id}}">{{toolname.toolname}}</option>
        {% else %}
        <option value="{{toolname.id}}">{{toolname.toolname}}</option>
          {% endif %}
        {% endfor %}
      </select>

      <div>
        
        <input type="submit" value="제출" />
      </div>
    </form>
    <a href="{% url 'swidea:home' %}">home</a>
    <script>
        a = document.getElementById("input_check")
        if(a == 1) {
            document.getElementById("input_check_hidden").disabled = true;
        }
        console.log('안녕')
    </script>
  </body>
</html>

<!-- <input type="checkbox" name="check" id="check"> <label for="checl">clear</label> -->